version = 1

[snip-snap]
project = "SnipSnap.xcodeproj"
scheme = "SnipSnap"
delivery = ["scripts/run.sh"]

[snip-snap-ios]
project = "SnipSnap.xcodeproj"
scheme = "SnipSnapiOS"
delivery = ["scripts/run.sh"]
